### ISSUE TITLE
KO - UNAUTHORIZED

### ISSUE THREAD

**Issue by whydie** [NinjaSnail1080/akinator.py#12]
If i try to run script from example, then i get this problem. 
btw Response-object have 500 status code in this case

```
Traceback (most recent call last):
  File "server.py", line 5, in <module>
    q = aki.start_game()
  File "C:\Users\whydie\Desktop\jinbot\venv\lib\site-packages\akinator\akinator.py", line 136, in start_game
    resp = self._parse_response(r.text)
  File "C:\Users\whydie\Desktop\jinbot\venv\lib\site-packages\akinator\akinator.py", line 86, in _parse_response
    return json.loads(",".join(response.split("(")[1::])[:-1])
  File "C:\Users\whydie\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\whydie\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\whydie\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

But if i open "new_session"-url that your code make, then i get another problem

`{["completion" => "KO - UNAUTHORIZED"]}`

**Comment by NinjaSnail1080** [comment]
Should be fixed in the new version
