### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by srevinsaju** [NinjaSnail1080/akinator.py#13]
Still something is going wrong
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/srevinsaju/.local/lib/python3.8/site-packages/akinator/akinator.py", line 136, in start_game
    resp = self._parse_response(r.text)
  File "/home/srevinsaju/.local/lib/python3.8/site-packages/akinator/akinator.py", line 86, in _parse_response
    return json.loads(",".join(response.split("(")[1::])[:-1])
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mouncg** [comment]
same here ;-;

**Comment by NinjaSnail1080** [comment]
Should be fixed in the new version
