### ISSUE TITLE
Error with ru lang (akinator.exceptions.AkiTimedOut: Your Akinator session has timed out)

### ISSUE THREAD

**Issue by LEv145** [NinjaSnail1080/akinator.py#16]
Standard test code:
```py
import akinator

aki = akinator.Akinator()

q = aki.start_game('ru')

while aki.progression <= 80:
    a = input(q + "\n\t")
    if a == "b":
        try:
            q = aki.back()
        except akinator.CantGoBackAnyFurther:
            pass
    else:
        q = aki.answer(a)
aki.win()

correct = input(f"It's {aki.first_guess['name']} ({aki.first_guess['description']})! Was I correct?\n{aki.first_guess['absolute_picture_path']}\n\t")
if correct.lower() == "yes" or correct.lower() == "y":
    print("Yay\n")
else:
    print("Oof\n")
```
Output:
```
https://ru.akinator.com
	y
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    q = aki.answer(a)
  File "/home/lev145/.local/lib/python3.8/site-packages/akinator/akinator.py", line 190, in answer
    return raise_connection_error(resp["completion"])
  File "/home/lev145/.local/lib/python3.8/site-packages/akinator/utils.py", line 117, in raise_connection_error
    raise AkiTimedOut("Your Akinator session has timed out")
akinator.exceptions.AkiTimedOut: Your Akinator session has timed out
```

**Comment by LEv145** [comment]
I found out why the bug
The fact is that the parser in _auto_get_region() gets a url that does not work normally with the server

URL:
https://srv12.akinator.com:9398/ws

You can temporarily solve the problem in this way:
```py
    def _auto_get_region(self, lang, theme):
        """Automatically get the uri and server from akinator.com for the specified language and theme"""

        server_regex = re.compile(
            "[{\"translated_theme_name\":\"[\s\S]*\",\"urlWs\":\"https:\\\/\\\/srv[0-9]+\.akinator\.com:[0-9]+\\\/ws\",\"subject_id\":\"[0-9]+\"}]")
        uri = lang + ".akinator.com"
        r = requests.get("https://" + uri)

        match = server_regex.search(r.text)
        parsed = json.loads(match.group().split("'arrUrlThemesToPlay', ")[-1])

        if lang == "ru":
            return {"uri": uri, "server": 'https://srv9.akinator.com:9386/ws'}

        if theme == "c":
            return {"uri": uri, "server": next((i for i in parsed if i["subject_id"] == "1"), None)["urlWs"]}
        elif theme == "a":
            return {"uri": uri, "server": next((i for i in parsed if i["subject_id"] == "14"), None)["urlWs"]}
        elif theme == "o":
            return {"uri": uri, "server": next((i for i in parsed if i["subject_id"] == "2"), None)["urlWs"]}
```

**Comment by NinjaSnail1080** [comment]
The latest update should fix this issue

**Comment by m1raynee** [comment]
Well, this appears again. Сould using an async client be the reason?

**Comment by NinjaSnail1080** [comment]
Does it happen when you try to start a game with the `ru` lang, or when you try to answer a question?

At this point I'm pretty sure it's a region thing. I live in the U.S. and I've never encountered this issue while testing.

**Comment by m1raynee** [comment]
Everything looks the same as last time. I do exactly the same thing as [here](https://github.com/NinjaSnail1080/akinator.py/issues/16#issue-808180031).
Also, I live in Russia, and on my local machine this issue doesn't appears, but on my remote host this occurred. My remote host is somewhere in Europe (not exactly specified anywhere).

**Comment by rdfsx** [comment]
Any solutions?
