### ISSUE TITLE
The language parameter is not working

### ISSUE THREAD

**Issue by celsoannes** [NinjaSnail1080/akinator.py#27]
When I set `language=pt` I get the follow error:

```
Traceback (most recent call last):
  File "/root/test_async.py", line 31, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/test_async.py", line 10, in main
    q = await aki.start_game(language=pt, child_mode=False)
NameError: name 'pt' is not defined
```

Here is my code:

```
"""A simple test of the async Akinator class"""

from akinator.async_aki import Akinator
import akinator
import asyncio

aki = Akinator()

async def main():
    q = await aki.start_game(language=pt, child_mode=False)

    while aki.progression <= 80:
        a = input(q + "\n\t")
        if a == "b":
            try:
                q = await aki.back()
            except akinator.CantGoBackAnyFurther:
                pass
        else:
            q = await aki.answer(a)
    await aki.win()

    correct = input(f"It's {aki.first_guess['name']} ({aki.first_guess['description']})! Was I correct?\n{aki.first_guess['absolute_picture_path']}\n\t")
    if correct.lower() == "yes" or correct.lower() == "y":
        print("Yay\n")
    else:
        print("Oof\n")
    await aki.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by Pysics** [comment]
@celsoannes `pt` is a variable, which is not defined.
Try setting `language="pt"` (with the quotes), which makes it a string.

**Comment by celsoannes** [comment]
> @celsoannes `pt` is a variable, which is not defined. Try setting `language="pt"` (with the quotes), which makes it a string.

Thanks, it worked.

I still have to give the answer in english:

```
root@akinator:~# python3 test_async.py
O seu personagem mora no Brasil?
        não
Traceback (most recent call last):
  File "/root/test_async.py", line 31, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/test_async.py", line 20, in main
    q = await aki.answer(a)
  File "/usr/local/lib/python3.9/dist-packages/akinator/async_aki/async_akinator.py", line 196, in answer
    ans = ans_to_id(ans)
  File "/usr/local/lib/python3.9/dist-packages/akinator/utils.py", line 43, in ans_to_id
    raise InvalidAnswerError("""
akinator.exceptions.InvalidAnswerError:
        You put "não", which is an invalid answer.
        The answer must be one of these:
            - "yes" OR "y" OR "0" for YES
            - "no" OR "n" OR "1" for NO
            - "i" OR "idk" OR "i dont know" OR "i don't know" OR "2" for I DON'T KNOW
            - "probably" OR "p" OR "3" for PROBABLY
            - "probably not" OR "pn" OR "4" for PROBABLY NOT

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f08d6514430>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f08d652dc40>, 67675.63982704)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f08d6514370>
```

And when it got the right answer it get so exciting that give part of the answer in english, hehehe.

```
root@akinator:~# python3 test_async.py
O seu personagem é brasileiro?
        no
O seu personagem é do Japão?
        no
O seu personagem é uma mulher?
        no
O seu personagem é real?
        no
O seu personagem tem cabelo?
        yes
O seu personagem é de um filme?
        no
O seu personagem é de um jogo?
        no
O seu personagem faz parte de um anime ,animação japonesa)?
        no
O seu personagem é de um desenho animado?
        yes
O seu personagem é um herói?
        no
O seu personagem é uma criança?
        yes
O seu personagem tem um irmão ou irmã?
        no
O seu personagem usa algo na cabeça?
        yes
O seu personagem é mexicano?
        no
O seu personagem é loiro/loira?
        yes
O seu personagem tem uma fada?
        no
O seu personagem está relacionada ao samba?
        no
O seu personagem é uma menina?
        yes
It's Masha (Masha e o Urso)! Was I correct?
https://photos.clarinea.fr/BL_4_pt/600/partenaire/l/3857742__958455997.jpg
        yes
Yay
```

**Comment by Pysics** [comment]
You can manually translate it if needed.

**Comment by celsoannes** [comment]
> You can manually translate it if needed.

Find it: /usr/local/lib/python3.9/dist-packages/akinator/utils.py

Thanks.

**Comment by Pysics** [comment]
I think this issue can be closed now.
