### ISSUE TITLE
Connection errror

### ISSUE THREAD

**Issue by michtesar** [NinjaSnail1080/akinator.py#4]
I encounter this error, when connecting.

```sh
Traceback (most recent call last):
  File "Desktop/test.py", line 26, in <module>
    main()
  File "Desktop/test.py", line 8, in main
    q = aki.start_game()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/akinator/akinator.py", line 112, in start_game
    return raise_connection_error(resp["completion"])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/akinator/utils.py", line 110, in raise_connection_error
    raise AkiConnectionFailure("An unknown error has occured. Server response: {}".format(response))
akinator.exceptions.AkiConnectionFailure: An unknown error has occured. Server response: KO - KEY NOT FOUND2
```

**Comment by NinjaSnail1080** [comment]
Working on it. Occasionally they change their servers and I need to update the lib with the new ones
