### ISSUE TITLE
Timeout Error: Errno 110 (Server is Incorrect In utils.py)

### ISSUE THREAD

**Issue by TollyThaWally** [NinjaSnail1080/akinator.py#7]
Starting today whenever I try to start an Akinator game I get the following error despite everything working fine before:

```Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 954, in create_connection
    raise exceptions[0]
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/lib64/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib64/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('62.210.100.133', 9162) 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 4247, in on_message
    q = await aki.start_game()
  File "/usr/local/lib/python3.7/site-packages/akinator/async_aki/async_akinator.py", line 129, in start_game
    async with session.get(NEW_SESSION_URL.format(self.server, self.timestamp, self.uid, self.frontaddr)) as w:
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection 
    req, traces, timeout)
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host srv2.akinator.com:9162 ssl:default [Connect call failed ('62.210.100.133', 9162)] ```

**Comment by TollyThaWally** [comment]
Seems that the server is incorrect in `utils.py`
Fixed by changing at line 62:
```
if lang is None or lang == "en" or lang == "english":
        return "srv2.akinator.com:9162"
```
To:
```
if lang is None or lang == "en" or lang == "english":
        return "srv14.akinator.com:9281"
```

**Comment by NinjaSnail1080** [comment]
Thanks for the notice. I went through and tested the other languages as well and updated the servers for `en_animals`, `en_objects`, `ar`, `kr`, and `pt`. I'm about to update the library to version 2.1.0 and fix these issues.
